"""Plot feature-level explanations for a synthetic gaze trajectory.

The functions in this module are intentionally independent from the runtime
CAPTCHA session. They take gaze points generated by ``HumanLikeEyeTracker`` and
render one figure per scoring feature so the diploma presentation can show how
raw ``(x, y, t)`` samples become feature scores.
"""

from __future__ import annotations

import math
import random
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, Mapping

try:
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    from matplotlib.patches import Arc, Circle, Rectangle
except ModuleNotFoundError:  # pragma: no cover - exercised only in minimal envs
    plt = None
    Arc = Circle = Rectangle = None

import config
from analysis.scorer import (
    angle_score,
    bounds_score,
    compute_angle_error,
    compute_distance_error,
    compute_latency,
    compute_out_of_bounds_ratio,
    distance_score,
    euclidean_distance,
    is_inside_bounds,
    latency_score,
)
from tracking.human_simulator import HumanLikeEyeTracker

GazePoint = tuple[float, float, float]


def _ensure_matplotlib() -> None:
    if plt is None:
        raise RuntimeError(
            "matplotlib is required for visualization. Install project dependencies from requirements.txt."
        )


@dataclass(frozen=True)
class FeatureVisualizationResult:
    """Paths and scores produced by a feature-visualization run."""

    output_dir: Path
    target_name: str
    target: tuple[float, float]
    stimulus_time: float
    gaze_points: list[GazePoint]
    feature_scores: dict[str, float]
    feature_values: dict[str, float | None]
    image_paths: dict[str, Path]


def generate_visualization_sample(
        target_name: str = "top_right",
        *,
        seed: int | None = 7,
        tracker: HumanLikeEyeTracker | None = None,
        start_time: float | None = None,
) -> tuple[list[GazePoint], float, tuple[float, float]]:
    """Generate a deterministic demo trajectory with ``HumanLikeEyeTracker``.

    ``HumanLikeEyeTracker`` uses Python's global ``random`` module. For a stable
    visualization in docs and slides, this helper optionally seeds it before
    collecting gaze points.
    """

    if target_name not in config.CORNERS:
        raise ValueError(f"Unknown target_name: {target_name!r}")

    if seed is not None:
        random.seed(seed)

    target = config.CORNERS[target_name]
    stimulus_time = time.time() if start_time is None else start_time
    eye_tracker = tracker or HumanLikeEyeTracker()
    gaze_points = eye_tracker.collect(
        start_time=stimulus_time,
        duration=config.STIMULUS_DURATION,
        target=target,
    )

    return gaze_points, stimulus_time, target


def render_feature_visualizations(
        gaze_points: Iterable[GazePoint] | None = None,
        *,
        target_name: str = "top_right",
        target: tuple[float, float] | None = None,
        stimulus_time: float | None = None,
        output_dir: str | Path = "visualization/output",
        seed: int | None = 7,
) -> FeatureVisualizationResult:
    """Render all feature-explanation plots and return generated paths.

    If ``gaze_points`` is not provided, the function generates them with
    ``HumanLikeEyeTracker``. This keeps the module usable both as a standalone
    demo and as a renderer for trajectories collected elsewhere.
    """

    _ensure_matplotlib()

    if gaze_points is None:
        generated, generated_time, generated_target = generate_visualization_sample(
            target_name=target_name,
            seed=seed,
            start_time=stimulus_time,
        )
        gaze = generated
        stimulus_time = generated_time
        target = generated_target
    else:
        gaze = list(gaze_points)
        if target is None:
            if target_name not in config.CORNERS:
                raise ValueError(f"Unknown target_name: {target_name!r}")
            target = config.CORNERS[target_name]
        if stimulus_time is None:
            stimulus_time = gaze[0][2] if gaze else time.time()

    if len(gaze) < 2:
        raise ValueError("At least two gaze points are required for visualization")

    out_dir = Path(output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    target_x, target_y = target
    feature_values = _compute_feature_values(gaze, target_x, target_y, stimulus_time)
    feature_scores = _compute_feature_scores(feature_values)

    paths = {
        "latency": out_dir / "01_latency_steps_cumulative_path.png",
        "distance_error": out_dir / "02_distance_error_trajectory_circles.png",
        "out_of_bounds_ratio": out_dir / "03_out_of_bounds_points_box.png",
        "angle_error": out_dir / "04_angle_error_vectors_arc.png",
        "feature_contribution": out_dir / "05_feature_contribution_pie.png",
    }

    plot_latency_analysis(gaze, stimulus_time, paths["latency"])
    plot_distance_error(gaze, target_x, target_y, paths["distance_error"])
    plot_out_of_bounds_ratio(gaze, target_x, target_y, stimulus_time, paths["out_of_bounds_ratio"])
    plot_angle_error(gaze, target_x, target_y, paths["angle_error"])
    plot_feature_contribution(feature_scores, paths["feature_contribution"])

    return FeatureVisualizationResult(
        output_dir=out_dir,
        target_name=target_name,
        target=target,
        stimulus_time=stimulus_time,
        gaze_points=gaze,
        feature_scores=feature_scores,
        feature_values=feature_values,
        image_paths=paths,
    )


def plot_latency_analysis(
        gaze_points: list[GazePoint],
        stimulus_time: float,
        output_path: str | Path,
        *,
        min_step: float = 6,
        min_steps_count: int = 3,
        total_threshold: float = 20,
) -> Path:
    """Plot per-step movement, cumulative path and latency thresholds."""

    _ensure_matplotlib()
    output_path = Path(output_path)
    step_times, step_distances, cumulative = _step_profile(gaze_points, stimulus_time)
    latency = compute_latency(
        gaze_points,
        stimulus_time,
        min_step=min_step,
        min_steps_count=min_steps_count,
        total_threshold=total_threshold,
    )

    fig, ax1 = plt.subplots(figsize=(12, 7))
    ax1.bar(step_times, step_distances, width=0.025, color="#38BDF8", alpha=0.75, label="Шаг между точками")
    ax1.axhline(min_step, color="#FDE047", linestyle="--", linewidth=2, label=f"min_step = {min_step}px")
    ax1.set_xlabel("Время после стимула, сек")
    ax1.set_ylabel("Длина шага, px")
    ax1.grid(alpha=0.25)

    ax2 = ax1.twinx()
    ax2.plot(step_times, cumulative, color="#A78BFA", linewidth=3, marker="o", label="Накопленный путь")
    ax2.axhline(total_threshold, color="#FB7185", linestyle=":", linewidth=2, label=f"total_threshold = {total_threshold}px")
    ax2.set_ylabel("Накопленный путь, px")

    if latency is not None:
        ax1.axvline(latency, color="#22C55E", linewidth=3, label=f"latency = {latency:.3f}s")

    ax1.axvspan(config.MIN_LATENCY, config.OPT_LATENCY, color="#22C55E", alpha=0.08, label="Оптимальная зона latency")
    ax1.axvline(config.MIN_LATENCY, color="#94A3B8", linestyle="--", linewidth=1.5)
    ax1.axvline(config.OPT_LATENCY, color="#94A3B8", linestyle="--", linewidth=1.5)
    ax1.axvline(config.MAX_LATENCY, color="#94A3B8", linestyle="--", linewidth=1.5)

    _combined_legend(ax1, ax2)
    plt.title("Latency: шаги движения + накопленный путь + пороги")
    fig.tight_layout()
    fig.savefig(output_path, dpi=160)
    plt.close(fig)
    return output_path


def plot_distance_error(
        gaze_points: list[GazePoint],
        target_x: float,
        target_y: float,
        output_path: str | Path,
) -> Path:
    """Plot gaze trajectory and distance rings around the target."""

    _ensure_matplotlib()
    output_path = Path(output_path)
    xs = [x for x, _, _ in gaze_points]
    ys = [y for _, y, _ in gaze_points]
    distances = [euclidean_distance(x, y, target_x, target_y) for x, y, _ in gaze_points]
    mean_distance = sum(distances) / len(distances)

    fig, ax = plt.subplots(figsize=(12, 7))
    _setup_screen_axes(ax)
    ax.plot(xs, ys, color="#38BDF8", linewidth=2, alpha=0.75)
    scatter = ax.scatter(xs, ys, c=distances, cmap="viridis", s=60, edgecolor="#E5E7EB", linewidth=0.5)
    ax.scatter([target_x], [target_y], marker="*", s=280, color="#FDE047", edgecolor="#111827", label="Цель")

    ring_radii = [config.BOUND_BOX_WIDTH / 2, mean_distance, max(distances)]
    ring_labels = ["граница box/2", f"mean error = {mean_distance:.1f}px", f"max = {max(distances):.1f}px"]
    ring_colors = ["#22C55E", "#FDE047", "#FB7185"]
    for radius, label, color in zip(ring_radii, ring_labels, ring_colors):
        ax.add_patch(Circle((target_x, target_y), radius, fill=False, color=color, linewidth=2, linestyle="--", label=label))

    ax.legend(loc="lower left")
    fig.colorbar(scatter, ax=ax, label="Расстояние до цели, px")
    plt.title("Distance error: траектория + круги расстояний вокруг цели")
    fig.tight_layout()
    fig.savefig(output_path, dpi=160)
    plt.close(fig)
    return output_path


def plot_out_of_bounds_ratio(
        gaze_points: list[GazePoint],
        target_x: float,
        target_y: float,
        stimulus_time: float,
        output_path: str | Path,
) -> Path:
    """Plot inside/outside points for the target bounding box."""

    _ensure_matplotlib()
    output_path = Path(output_path)
    valid_points = [point for point in gaze_points if point[2] - stimulus_time >= config.LATENCY_WINDOW]
    plotted_points = valid_points or gaze_points
    inside = [is_inside_bounds(x, y, target_x, target_y) for x, y, _ in plotted_points]
    out_ratio = compute_out_of_bounds_ratio(gaze_points, target_x, target_y, stimulus_time)

    fig, ax = plt.subplots(figsize=(12, 7))
    _setup_screen_axes(ax)
    _draw_target_box(ax, target_x, target_y)
    ax.scatter([target_x], [target_y], marker="*", s=260, color="#FDE047", edgecolor="#111827", label="Цель")

    inside_points = [point for point, is_in in zip(plotted_points, inside) if is_in]
    outside_points = [point for point, is_in in zip(plotted_points, inside) if not is_in]

    if inside_points:
        ax.scatter(
            [x for x, _, _ in inside_points],
            [y for _, y, _ in inside_points],
            color="#22C55E",
            s=70,
            label="Внутри box",
        )
    if outside_points:
        ax.scatter(
            [x for x, _, _ in outside_points],
            [y for _, y, _ in outside_points],
            color="#FB7185",
            s=70,
            label="Снаружи box",
        )

    ax.plot([x for x, _, _ in gaze_points], [y for _, y, _ in gaze_points], color="#94A3B8", linewidth=1.5, alpha=0.5)
    ax.text(
        0.02,
        0.96,
        f"out_of_bounds_ratio = {out_ratio:.2f}\nLATENCY_WINDOW = {config.LATENCY_WINDOW}s",
        transform=ax.transAxes,
        va="top",
        bbox={"boxstyle": "round", "facecolor": "#111827", "edgecolor": "#38BDF8", "alpha": 0.9},
        color="#E5E7EB",
    )
    ax.legend(loc="lower left")
    plt.title("Out-of-bounds ratio: точки внутри/снаружи box с цветовой кодировкой")
    fig.tight_layout()
    fig.savefig(output_path, dpi=160)
    plt.close(fig)
    return output_path


def plot_angle_error(
        gaze_points: list[GazePoint],
        target_x: float,
        target_y: float,
        output_path: str | Path,
) -> Path:
    """Plot actual/target vectors and an arc for angle error."""

    _ensure_matplotlib()
    output_path = Path(output_path)
    x0, y0, _ = gaze_points[0]
    x1, y1, _ = gaze_points[-1]
    angle = compute_angle_error(gaze_points, target_x, target_y)

    fig, ax = plt.subplots(figsize=(12, 7))
    _setup_screen_axes(ax)
    ax.plot([x for x, _, _ in gaze_points], [y for _, y, _ in gaze_points], color="#38BDF8", linewidth=2, alpha=0.5)
    ax.scatter([x0], [y0], s=120, color="#A78BFA", label="Старт")
    ax.scatter([x1], [y1], s=120, color="#22D3EE", label="Последняя точка")
    ax.scatter([target_x], [target_y], marker="*", s=280, color="#FDE047", edgecolor="#111827", label="Цель")

    ax.annotate("", xy=(x1, y1), xytext=(x0, y0), arrowprops={"arrowstyle": "->", "color": "#22D3EE", "lw": 3})
    ax.annotate("", xy=(target_x, target_y), xytext=(x0, y0), arrowprops={"arrowstyle": "->", "color": "#FDE047", "lw": 3})

    _draw_angle_arc(ax, (x0, y0), (x1, y1), (target_x, target_y), angle)
    ax.text(
        0.02,
        0.96,
        f"angle_error = {angle:.2f}°\nangle_score = {angle_score(angle):.2f}",
        transform=ax.transAxes,
        va="top",
        bbox={"boxstyle": "round", "facecolor": "#111827", "edgecolor": "#38BDF8", "alpha": 0.9},
        color="#E5E7EB",
    )
    ax.legend(loc="lower left")
    plt.title("Angle error: векторы движения + дуга угла отклонения")
    fig.tight_layout()
    fig.savefig(output_path, dpi=160)
    plt.close(fig)
    return output_path


def plot_feature_contribution(feature_scores: Mapping[str, float], output_path: str | Path) -> Path:
    """Plot weighted feature contributions to the final score."""

    _ensure_matplotlib()
    output_path = Path(output_path)
    labels = list(config.FEATURE_WEIGHTS.keys())
    contributions = [feature_scores[label] * config.FEATURE_WEIGHTS[label] for label in labels]
    total = sum(contributions)

    fig, ax = plt.subplots(figsize=(9, 7))
    colors = ["#38BDF8", "#A78BFA", "#FDE047", "#22C55E"]
    if total == 0:
        values = [1 for _ in labels]
        title_suffix = "total_score = 0.00"
    else:
        values = contributions
        title_suffix = f"total_score = {total:.2f}"

    pie_labels = [f"{label}\n{value:.3f}" for label, value in zip(labels, contributions)]
    ax.pie(values, labels=pie_labels, autopct="%1.1f%%", startangle=90, colors=colors)
    ax.axis("equal")
    plt.title(f"Вклад признаков в итоговый score ({title_suffix})")
    fig.tight_layout()
    fig.savefig(output_path, dpi=160)
    plt.close(fig)
    return output_path


def _compute_feature_values(
        gaze_points: list[GazePoint],
        target_x: float,
        target_y: float,
        stimulus_time: float,
) -> dict[str, float | None]:
    latency = compute_latency(gaze_points, stimulus_time)
    return {
        "latency": latency,
        "distance_error": compute_distance_error(gaze_points, target_x, target_y),
        "angle_error": compute_angle_error(gaze_points, target_x, target_y),
        "out_of_bounds_ratio": compute_out_of_bounds_ratio(gaze_points, target_x, target_y, stimulus_time),
    }


def _compute_feature_scores(feature_values: Mapping[str, float | None]) -> dict[str, float]:
    distance_error = feature_values["distance_error"]
    angle_error = feature_values["angle_error"]
    out_ratio = feature_values["out_of_bounds_ratio"]

    return {
        "latency": latency_score(feature_values["latency"]),
        "distance_error": distance_score(0.0 if distance_error is None else distance_error),
        "angle_error": angle_score(180.0 if angle_error is None else angle_error),
        "out_of_bounds_ratio": bounds_score(0.0 if out_ratio is None else out_ratio),
    }


def _step_profile(gaze_points: list[GazePoint], stimulus_time: float) -> tuple[list[float], list[float], list[float]]:
    step_times: list[float] = []
    step_distances: list[float] = []
    cumulative: list[float] = []
    total = 0.0
    for index in range(1, len(gaze_points)):
        x1, y1, _ = gaze_points[index - 1]
        x2, y2, t2 = gaze_points[index]
        step = math.hypot(x2 - x1, y2 - y1)
        total += step
        step_times.append(t2 - stimulus_time)
        step_distances.append(step)
        cumulative.append(total)
    return step_times, step_distances, cumulative


def _setup_screen_axes(ax) -> None:
    ax.set_xlim(-50, config.SCREEN_WIDTH + 50)
    ax.set_ylim(config.SCREEN_HEIGHT + 50, -50)
    ax.set_xlabel("X, px")
    ax.set_ylabel("Y, px")
    ax.grid(alpha=0.25)
    ax.set_facecolor("#F8FAFC")


def _draw_target_box(ax, target_x: float, target_y: float) -> None:
    half_w = config.BOUND_BOX_WIDTH / 2
    half_h = config.BOUND_BOX_HEIGHT / 2
    ax.add_patch(
        Rectangle(
            (target_x - half_w, target_y - half_h),
            config.BOUND_BOX_WIDTH,
            config.BOUND_BOX_HEIGHT,
            fill=False,
            edgecolor="#22C55E",
            linewidth=2.5,
            linestyle="--",
            label="Bounding box",
        )
    )


def _draw_angle_arc(
        ax,
        origin: tuple[float, float],
        actual: tuple[float, float],
        target: tuple[float, float],
        angle: float,
) -> None:
    ox, oy = origin
    actual_deg = math.degrees(math.atan2(actual[1] - oy, actual[0] - ox))
    target_deg = math.degrees(math.atan2(target[1] - oy, target[0] - ox))
    radius = min(
        math.hypot(actual[0] - ox, actual[1] - oy),
        math.hypot(target[0] - ox, target[1] - oy),
        260,
    )
    start, end = sorted([actual_deg, target_deg])
    if end - start > 180:
        start, end = end, start + 360
    ax.add_patch(Arc((ox, oy), radius, radius, angle=0, theta1=start, theta2=end, color="#FB7185", linewidth=3))
    mid = math.radians((start + end) / 2)
    ax.text(
        ox + math.cos(mid) * radius * 0.65,
        oy + math.sin(mid) * radius * 0.65,
        f"θ={angle:.1f}°",
        color="#FB7185",
        fontsize=14,
        weight="bold",
        )


def _combined_legend(ax1, ax2) -> None:
    handles1, labels1 = ax1.get_legend_handles_labels()
    handles2, labels2 = ax2.get_legend_handles_labels()
    ax1.legend(handles1 + handles2, labels1 + labels2, loc="upper left")
